name: cannonfamily
favicon: null
layout_spectrum: 0.8406913978978992
typography_spectrum: 0.6684533830266446
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.23644095030613244
  lightness: 0.10581396869383752
  saturation: 0.7191651354078203
  rhythmicContrast: 0.519738428061828
purpose: []
