name: The Cannon Family
favicon: null
layout_spectrum: 0
typography_spectrum: 1
title: The Cannon Family
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-64588142-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d1d1d'
    - '#575757'
    - '#d0d0d0'
    - '#767676'
    - '#a3a3a3'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
